### ISSUE TITLE
Assembly Notes

### ISSUE THREAD

**Issue by joshuamcginnis** [EverymanBio/pestalotiopsis#1]
# Assembly

### Using Canu v2.2
```
./bin/canu genomesize=45m \
-d /mnt/e/pestalotiopsis/assembly \
-p pestalotiopsis \
-nanopore /mnt/e/pestalotiopsis/guppy_sup_output/combined.fastq.gz \
&> /mnt/e/pestalotiopsis/canu.out
```

### Using flye v2.9-b1768
```
flye --nano-hq /mnt/e/pestalotiopsis/guppy_sup_output/combined.fastq.gz \
--genome-size=42m \
--out-dir /mnt/e/pestalotiopsis/assembly/flye \
--threads 16 \
&> /mnt/e/pestalotiopsis/assembly/flye/flye.out
```

# Polishing
##  Trimming contig_11 (5kb contig)
1. Create list of desired contigs without `contig_11` > `pestalotiopsis/assembly/subseq.lst`
```
contig_4
contig_6
contig_3
contig_8
contig_7
contig_5
contig_9
contig_1
contig_2
contig_10
```
2. Use `seqtk` to create fasta without `contig_11`
```
 ./seqtk subseq /mnt/e/pestalotiopsis/assembly/flye/assembly.fasta \
> /mnt/e/pestalotiopsis/assembly/subseq.lst \
> /mnt/e/pestalotiopsis/assembly/flye/assembly_no_contig_11.fasta
```

3. Run `minimap2` v2.22 to generate overlaps
```
 ./minimap2 -x map-ont -t 12 \
/mnt/e/pestalotiopsis/assembly/flye/assembly_no_contig_11.fasta \
/mnt/e/pestalotiopsis/guppy_sup_output/combined.fastq.gz > \
/mnt/e/pestalotiopsis/assembly/minimap2/overlaps.paf

[M::mm_idx_gen::1.464*1.01] collected minimizers
[M::mm_idx_gen::1.863*1.48] sorted minimizers
[M::main::1.863*1.48] loaded/built the index for 10 target sequence(s)
[M::mm_mapopt_update::1.988*1.45] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 10
[M::mm_idx_stat::2.079*1.44] distinct minimizers: 8359765 (94.64% are singletons); average occurrences: 1.065; average spacing: 5.352; total length: 47658561
[M::worker_pipeline::16.320*6.88] mapped 116002 sequences
[M::worker_pipeline::26.295*8.34] mapped 116374 sequences
[M::worker_pipeline::35.740*9.16] mapped 115079 sequences
[M::worker_pipeline::45.169*9.68] mapped 116765 sequences
[M::worker_pipeline::54.364*9.97] mapped 116479 sequences
[M::worker_pipeline::62.823*10.16] mapped 120016 sequences
[M::worker_pipeline::72.128*10.26] mapped 117458 sequences
[M::worker_pipeline::80.858*10.35] mapped 119949 sequences
[M::worker_pipeline::82.666*10.38] mapped 33873 sequences
[M::main] Version: 2.22-r1101
[M::main] CMD: ./minimap2 -x map-ont -t 12 /mnt/e/pestalotiopsis/assembly/flye/assembly_no_contig_11.fasta /mnt/e/pestalotiopsis/guppy_sup_output/combined.fastq.gz
[M::main] Real time: 82.701 sec; CPU: 857.953 sec; Peak RSS: 1.375 GB
```

3(b). Gzip the overlaps
`gzip /mnt/e/pestalotiopsis/assembly/minimap2/overlaps.paf`

4. Run `rakon` v.1.4.22
```
./build/bin/racon -t 16 \
/mnt/e/pestalotiopsis/guppy_sup_output/combined.fastq.gz \
/mnt/e/pestalotiopsis/assembly/minimap2/overlaps.paf.gz \
/mnt/e/pestalotiopsis/assembly/flye/assembly.fasta > \
/mnt/e/pestalotiopsis/assembly/rakon/corrected.fasta

[racon::Polisher::initialize] loaded target sequences 0.173205 s
[racon::Polisher::initialize] loaded sequences 67.255879 s
[racon::Polisher::initialize] loaded overlaps 2.016656 s
[racon::Polisher::initialize] aligning overlaps [====================] 141.591912 s
[racon::Polisher::initialize] transformed data into windows 6.779552 s
[racon::Polisher::polish] generating consensus [====================] 1084.741511 s
[racon::Polisher::] total = 1309.127294 s
```

5. Run `medeka` v1.4.4

Note: it seems medaka does not like gzipped (prefers bzip) for the -d rakon input for whatever reason, so had to run it on ungzipped file. Oddly, gzip worked fine for the raw reads input.

```
medaka_consensus -i /mnt/e/pestalotiopsis/guppy_sup_output/combined.fastq.gz \                    
-d /mnt/e/pestalotiopsis/assembly/rakon/corrected.fasta \
-o /mnt/e/pestalotiopsis/assembly/medaka
```

# Annotation
Using `liftoff` v1.6.1

```
liftoff -g Pestal1_GeneCatalog_20180925.gff3 \
> -o gene_catalog \
> ../ncbi/consensus.fasta \
> Pestal1_AssemblyScaffolds.fasta
```

**Comment by joshuamcginnis** [comment]
@dgiguer medaka does a lot so not sure if what I did was the thing needed, but `medaka_consensus` just finished and all files are syncing to s3 currently.

**Comment by dgiguer** [comment]
Excellent! medaka_consensus is the one, and the polished output should be in medaka/consensus.fasta !

**Comment by joshuamcginnis** [comment]
Cool. I see all 10 contigs and roughly `47674553` bp. 

Any ideas why all my primer searches are coming up blank? Here's the pair I used to barcode it, for example:

F: `CTTGGTCATTTAGAGGAAGTAA`
R: `TCCTCCGCTTATTGATATGC`

Although, I am able to find long subsets of the [barcoding sequence](https://www.ncbi.nlm.nih.gov/nuccore/MW795652) itself.

**Comment by dgiguer** [comment]
Not entirely sure - would need more info on how you're looking for them (string matching, alignment, etc). I think it may be easier to annotate the genome then pull out the ITS region vs. aligning primers against it. For this I think we could use MetaEuk or MMSeqs2. 

I just ran BUSCO: 

```
# busco v5.2.2
busco -m genome -l sordariomycetes_odb10 -i consensus.fasta -o busco_output --cpu 14 
2021-10-20 16:18:46 INFO:	***** Start a BUSCO v5.2.2 analysis, current time: 10/20/2021 16:18:46 *****
2021-10-20 16:18:46 INFO:	Configuring BUSCO with local environment
2021-10-20 16:18:46 INFO:	Mode is genome
2021-10-20 16:18:46 INFO:	Downloading information on latest versions of BUSCO data...
2021-10-20 16:18:47 INFO:	Input file is /home/dangiguere/Documents/everymanbio/polished_assembly/consensus.fasta
2021-10-20 16:18:47 INFO:	Downloading file 'https://busco-data.ezlab.org/v5/data/lineages/sordariomycetes_odb10.2020-08-05.tar.gz'
2021-10-20 16:19:24 INFO:	Decompressing file '/home/dangiguere/Documents/everymanbio/polished_assembly/busco_downloads/lineages/sordariomycetes_odb10.tar.gz'
2021-10-20 16:19:31 INFO:	Running BUSCO using lineage dataset sordariomycetes_odb10 (eukaryota, 2020-08-05)
2021-10-20 16:19:32 INFO:	Running 1 job(s) on metaeuk, starting at 10/20/2021 16:19:32
2021-10-20 16:20:28 INFO:	[metaeuk]	1 of 1 task(s) completed
2021-10-20 16:20:30 INFO:	***** Run HMMER on gene sequences *****
2021-10-20 16:20:30 INFO:	Running 3817 job(s) on hmmsearch, starting at 10/20/2021 16:20:30
2021-10-20 16:20:35 INFO:	[hmmsearch]	382 of 3817 task(s) completed
2021-10-20 16:20:42 INFO:	[hmmsearch]	764 of 3817 task(s) completed
2021-10-20 16:20:50 INFO:	[hmmsearch]	1146 of 3817 task(s) completed
2021-10-20 16:20:56 INFO:	[hmmsearch]	1527 of 3817 task(s) completed
2021-10-20 16:21:01 INFO:	[hmmsearch]	1909 of 3817 task(s) completed
2021-10-20 16:21:06 INFO:	[hmmsearch]	2291 of 3817 task(s) completed
2021-10-20 16:21:11 INFO:	[hmmsearch]	2672 of 3817 task(s) completed
2021-10-20 16:21:14 INFO:	[hmmsearch]	3054 of 3817 task(s) completed
2021-10-20 16:21:17 INFO:	[hmmsearch]	3436 of 3817 task(s) completed
2021-10-20 16:21:22 INFO:	[hmmsearch]	3817 of 3817 task(s) completed
2021-10-20 16:21:22 INFO:	Extracting missing and fragmented buscos from the file refseq_db.faa...
2021-10-20 16:21:23 INFO:	Running 1 job(s) on metaeuk, starting at 10/20/2021 16:21:23
2021-10-20 16:23:17 INFO:	[metaeuk]	1 of 1 task(s) completed
2021-10-20 16:23:18 INFO:	***** Run HMMER on gene sequences *****
2021-10-20 16:23:18 INFO:	Running 119 job(s) on hmmsearch, starting at 10/20/2021 16:23:18
2021-10-20 16:23:18 INFO:	[hmmsearch]	12 of 119 task(s) completed
2021-10-20 16:23:18 INFO:	[hmmsearch]	24 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	36 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	48 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	60 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	72 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	84 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	96 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	108 of 119 task(s) completed
2021-10-20 16:23:19 INFO:	[hmmsearch]	119 of 119 task(s) completed
2021-10-20 16:23:28 INFO:	Validating exons and removing overlapping matches
2021-10-20 16:23:35 INFO:	Results:	C:97.9%[S:97.5%,D:0.4%],F:0.6%,M:1.5%,n:3817	   

2021-10-20 16:23:35 INFO:	

	--------------------------------------------------
	|Results from dataset sordariomycetes_odb10       |
	--------------------------------------------------
	|C:97.9%[S:97.5%,D:0.4%],F:0.6%,M:1.5%,n:3817     |
	|3739	Complete BUSCOs (C)                       |
	|3722	Complete and single-copy BUSCOs (S)       |
	|17	Complete and duplicated BUSCOs (D)        |
	|23	Fragmented BUSCOs (F)                     |
	|55	Missing BUSCOs (M)                        |
	|3817	Total BUSCO groups searched               |
	--------------------------------------------------
2021-10-20 16:23:35 INFO:	BUSCO analysis done. Total running time: 288 seconds
2021-10-20 16:23:35 INFO:	Results written in /home/dangiguere/Documents/everymanbio/polished_assembly/busco_output
2021-10-20 16:23:35 INFO:	For assistance with interpreting the results, please consult the userguide: https://busco.ezlab.org/busco_userguide.html

2021-10-20 16:23:35 INFO:	Visit this page https://gitlab.com/ezlab/busco#how-to-cite-busco to see how to cite BUSCO
```

97.9% complete is essentially perfect. This means the polishing likely fixed truncated exons from the raw assembly. Edit: just pushed the data to S3!

**Comment by joshuamcginnis** [comment]
I just did string matching, e.g. `$ ag "CTTGGTCATTTAGAGGAAGTAA" consensus.fasta`. Odd that there wasn't even a single match. Dang boy, you keep introducing a new tool with every reply! Haha. I don't know what busco is but glad it's spitting out great results.

Roger on the s3. On that note, we should find a place to pause at some point and plan to do some tar + gz somewhere along the way to help me save on storage costs.

**Comment by dgiguer** [comment]
Try doing an alignment instead of string matching (e.g., you could install BLAST via conda and create a database using the genome and align the primers against the genome database with blastn). If there's a single base wrong in either sequence, then string matching may not find it! Especially if the medaka output only has 80 characters per line - there may be a line break character in the middle of the sequence prevent the string match (although I don't know if that would effect `ag`). 

Also, I've synced to local so all good if you want to tar.gz everything!

**Comment by joshuamcginnis** [comment]
The consensus fasta doesn't have any newlines (aside from the fasta headers) or col limits so str searching _should_ work. Here's an example blast result against the local consensus database using the forward ITS primer above. Looks like multiple matches with single nucleotide differences across the contigs. 

![query](https://user-images.githubusercontent.com/391074/138348327-cabb1c90-663e-4dd5-9af8-a7485dc66342.jpg)

Doesn't really tell a whole lot. That sequence is highly conserved so I'd think it should be present unless the base caller misinterpreted the underlying signal data? 🤷‍♂️

**Comment by joshuamcginnis** [comment]
I can't seem to get any alignments when running `blastn` directly, no matter how short the sequence. I tried a whole bunch of options like window and word_size to no avail. I'm guessing some sort of index is missing since the search results return almost immediately. 

P.S. I wiped the s3 /assembly dir before I saw that you had uploaded your busco results there. 

```
$ makeblastdb -in consensus.fasta -dbtype nucl -title pestalotiopsis -parse_seqids -out pestalotiopsis
               
Building a new DB, current time: 10/21/2021 19:10:01
New DB name:   /mnt/e/ncbi/pestalotiopsis
New DB title:  pestalotiopsis
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 10 sequences in 0.370598 seconds.
```

```
$ cat query.fasta
>example
CTT
```

```
blastn -query query.fasta -db pestalotiopsis
BLASTN 2.9.0+

Reference: Zheng Zhang, Scott Schwartz, Lukas Wagner, and Webb
Miller (2000), "A greedy algorithm for aligning DNA sequences", J
Comput Biol 2000; 7(1-2):203-14.

Database: pestalotiopsis
           10 sequences; 47,674,442 total letters
Query= example
Length=3

***** No hits found *****

Lambda      K        H
    1.33    0.621     1.12

Gapped
Lambda      K        H
    1.28    0.460    0.850

Effective search space used: 143023326

  Database: pestalotiopsis
    Posted date:  Oct 21, 2021  7:10 PM
  Number of letters in database: 47,674,442
  Number of sequences in database:  10

Matrix: blastn matrix 1 -2
Gap Penalties: Existence: 0, Extension: 2.5

**Comment by joshuamcginnis** [comment]
@dgiguer 

The ref assembly [GCA_018115615.1](https://www.ncbi.nlm.nih.gov/assembly/GCA_018115615.1) you liked doesn't appear to have an annotation file (gff/gtf) available to download. The only other one I could find in NIH that did was [GCF_000516985.1](https://www.ncbi.nlm.nih.gov/assembly/GCF_000516985.1).

I went ahead and ran liftoff against a newer [alternate assembly](https://mycocosm.jgi.doe.gov/Pestal1/Pestal1.info.html) from Mycocasm and uploaded the results to: `s3://everymanbio-data/annotation/gene_catalog`

I found matches for some of the loci used in barcoding, with the exception of ITS. I'm not really sure how that'd be annotated or if we'd have to manually look between the regions coding for the small - large rRNA.

I did; however, find some annotations for beta tubulin and translation elongation factor 1, the secondary barcode regions recommended to me for verifying species.

```
$ ag 'beta tubulin' gene_catalog
43716:contig_4  Liftoff gene    5756686 5758496 .       -       .       
ID=gene_1654;Name=jgi.p|Pestal1|508877;portal_id=Pestal1;product_name=beta tubulin;
proteinId=508877;
transcriptId=509297;coverage=0.999;sequence_ID=0.910;valid_ORFs=1;extra_copy_number=0;copy_num_ID=gene_1654_0

$ ag 'elongation factor tu' gene_catalog
108143:contig_8 Liftoff gene    1337321 1339380 .       +       .       
ID=gene_5830;Name=jgi.p|Pestal1|623221;portal_id=Pestal1;product_name=translation elongation factor Tu;
proteinId=623221;
transcriptId=623641;coverage=0.998;sequence_ID=0.982;valid_ORFs=1;extra_copy_number=0;copy_num_ID=gene_5830_0
```

If I'm understanding correctly, it's saying the beta tubulin sequence is in `contig_4` between nts `5756686:5758496`? I took a stab at trying to use `seqkit` to extract that via `$ cat ../ncbi/consensus.fasta | seqkit subseq -r 5756686:5758496`

It seemed to return `5756686:5758496` for _all_ contigs. I tried BLASTing the one for `contig_4`, but it came back with no matches.

Can you spot check what I did? Perhaps I'm not extracting the subseq correctly. Thank you!

**Comment by dgiguer** [comment]
Nice! That assembly looks pretty high quality so the annotation should be a good start as well. Good find!

For ITS: Yea you'll probably have to manually extract the region, but hopefully the LiftOff annotated the regions of the rRNA genes to make it easier. 

For `seqkit`, try adding the `--chr contig_4` to select from the specific contig!

**Comment by joshuamcginnis** [comment]
I tried every combination of `--chr` I could but it still keeps returning all records. For example, this prints out the first 5 chars from all contigs: `cat ../ncbi/consensus.fasta | seqkit subseq --chr contig_1 -r 1:5` Do you see the same?

**Comment by joshuamcginnis** [comment]
I think we've covered everything now and our notes are documented in the README.
