### ISSUE TITLE
NIH Submission

### ISSUE THREAD

**Issue by joshuamcginnis** [EverymanBio/pestalotiopsis#2]
BioProject ID:      PRJNA773800
BioSample accession: SAMN22513219
Temporary SubmissionID: SUB10553887

Submission instructions: https://www.ncbi.nlm.nih.gov/assembly/docs/submission/

* Confirm we fall under the category: `Submitting a haploid assembly: submitting WGS contigs and pseudo-molecules (chromosomes and/or scaffolds)`?

**Comment by dgiguer** [comment]
Yes, haploid is right!
